FROM node:18-alpine3.15 AS builder
WORKDIR /app
COPY ./ ./
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
RUN npm run build

FROM node:18-alpine3.15 
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
EXPOSE 9001
CMD ["npm", "run", "dev"]