version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dist:/app/dist
    ports:
      - '8080:8080'
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Shoppie
    ports:
      - 27017:27017
volumes:
  mongodata:
  dist:
