version: '3'

services:
  es:
    labels:
      com.example.service: 'es'
      com.example.description: 'For searching and indexing data'
    image: elasticsearch:5.4
    container_name: shoppieES
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
    ports:
      - '9200:9200'

  logstash:
    labels:
      com.example.service: 'logstash'
      com.example.description: 'For logging data'
    image: logstash:5.4.3
    volumes:
      - ./:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - es
    ports:
      - '5959:5959'

  kibana:
    labels:
      com.example.service: 'kibana'
      com.example.description: 'Data visualisation and for log aggregation'
    image: kibana:5.4.3
    container_name: shoppie_kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dist:/app/dist
    ports:
      - '8080:8080'
    depends_on:
      - es
      - kibana
    environment:
      - LOGSTASH_HOST=logstash
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Shoppie
    ports:
      - 27017:27017
volumes:
  mongodata:
  dist:
  esdata:
  logstash:
